version: '3.5'

services:
  dokuwiki-nginx:
    image: 'docker.io/bitnami/dokuwiki:20200729-debian-10'
    volumes:
      - /bitnami/dokuwiki:/bitnami/dokuwiki
    networks:
      - public

    hostname: dokuwiki-nginx
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 1


networks:
  public:
    external: true
