version: '3.5'

services:
  nginx:
    image: necromant/dokuwiki-nginx
    depends_on:
      - php-fpm
    networks:
      - public
      - private

    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 2

  php-fpm:
    image: necromant/dokuwiki-php-fpm
    networks:
      - public
      - private

    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 1


networks:
  public:
    external: true
  private:
