version: '3.5'

services:
  dokuwiki-nginx:
    image: 'docker.io/bitnami/dokuwiki:20200729-debian-10'
    volumes:
      - dokuwiki_data:/bitnami/dokuwiki
    networks:
      - public

    hostname: dokuwiki-nginx
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 1
    
volumes:
  dokuwiki_data:
    external: true

networks:
  public:
    external: true
