apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: dokuwiki-pvc
  name: dokuwiki-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: dokuwiki-sc
  resources:
    requests:
      storage: 1Gi
status: {}
