apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dokuwiki-pvc
spec:
  accessModes:
  - ReadWriteOnce
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /data/dokuwiki
    server: 10.50.0.3
  resources:
    requests:
      storage: 1Gi
status: {}
