apiVersion: v1
kind: PersistentVolume
metadata:
  name: dokuwiki-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: dokuwiki-sc
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /data/dokuwiki
    server: 10.50.0.3